/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "button_driver.h"
#include "led_driver.h"
#include "seven_segment_driver.h"
#include "timebase_driver.h"
#include "uart_driver.h"
#include "ldr_driver.h"

/* Private includes */

/* Private typedef */

/* Private enum */

/* Private struct */

/* Private union */

/* Private define */
#define MAIN_SEG7_UPDATE_INTERVAL_MS (1000U)
#define MAIN_SEG7_DIGIT_MAX          (9U)

/* Private macro */

/* Private constants */

/* Private variables */

/* External variables */

/* Private function prototypes */

/* Private user code */

/* Main function, if applicable */
int main(void)
{
    uint32_t digit_value;
    uint32_t previous_timestamp_ms;
    uint32_t current_timestamp_ms;

    LED_Init();
    BUTTON_Init();
    SEG7_Init();
    TIMEBASE_Init();

    /* Initialize LDR ADC (M06) */
    LDR_Init();

    /* Initialize UART (M05) and send startup diagnostic message */
    UART_Init();
    (void)UART_SendString("STM32 Train Simulator UART Ready\r\n");

    digit_value = 0U;
    previous_timestamp_ms = TIMEBASE_GetMilliseconds();
    SEG7_DisplayDigit(digit_value);

    while (1U)
    {
        current_timestamp_ms = TIMEBASE_GetMilliseconds();

        if ((current_timestamp_ms - previous_timestamp_ms) >= MAIN_SEG7_UPDATE_INTERVAL_MS)
        {
            previous_timestamp_ms = current_timestamp_ms;
            SEG7_DisplayDigit(digit_value);

            digit_value++;
            if (digit_value > MAIN_SEG7_DIGIT_MAX)
            {
                digit_value = 0U;
            }
        }

        /* UART RX processing: non-blocking echo diagnostic */
        if (UART_IsRxAvailable() > 0U)
        {
            char rxch;
            char response[8U];

            rxch = UART_ReadChar();

            response[0] = 'R';
            response[1] = 'X';
            response[2] = ':';
            response[3] = ' ';
            response[4] = rxch;
            response[5] = '\r';
            response[6] = '\n';
            response[7] = '\0';

            (void)UART_SendString(response);
        }

        /* LDR sampling: request conversion every 100 ms (non-blocking) */
        if ((current_timestamp_ms - previous_timestamp_ms) >= MAIN_SEG7_UPDATE_INTERVAL_MS)
        {
            /* reuse previous_timestamp_ms tick for 1000 ms seg7 update; do nothing here */
        }

        /* Use separate timestamps for LDR conversion and reporting */
        static uint32_t ldr_prev_conv_ts = 0U;
        static uint32_t ldr_prev_report_ts = 0U;

        /* Start conversion every 100 ms */
        if ((current_timestamp_ms - ldr_prev_conv_ts) >= 100U)
        {
            ldr_prev_conv_ts = current_timestamp_ms;
            LDR_StartConversion();
        }

        /* Report latest sample every 1000 ms */
        if ((current_timestamp_ms - ldr_prev_report_ts) >= 1000U)
        {
            ldr_prev_report_ts = current_timestamp_ms;

            if (LDR_IsSampleAvailable() != 0U)
            {
                uint32_t sample = LDR_GetRawValue();
                char outbuf[32U];
                uint32_t idx = 0U;

                /* Build string "LDR Raw: <num>\r\n" without printf */
                outbuf[idx++] = 'L';
                outbuf[idx++] = 'D';
                outbuf[idx++] = 'R';
                outbuf[idx++] = ' ';
                outbuf[idx++] = 'R';
                outbuf[idx++] = 'a';
                outbuf[idx++] = 'w';
                outbuf[idx++] = ':';
                outbuf[idx++] = ' ';

                /* Convert sample (0..4095) to decimal */
                uint32_t temp = sample;
                char digits[6U];
                uint32_t dig_cnt = 0U;

                if (temp == 0U)
                {
                    digits[dig_cnt++] = '0';
                }
                else
                {
                    while (temp > 0U)
                    {
                        uint32_t rem = temp % 10U;
                        digits[dig_cnt++] = (char)('0' + (int)rem);
                        temp = temp / 10U;
                    }
                }

                /* append digits in reverse */
                while (dig_cnt > 0U)
                {
                    dig_cnt--;
                    outbuf[idx++] = digits[dig_cnt];
                }

                outbuf[idx++] = '\r';
                outbuf[idx++] = '\n';
                outbuf[idx] = '\0';

                (void)UART_SendString(outbuf);
            }
        }
    }
}

/* Public functions */

/* Callback functions */

/* Private functions */

