/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "button_driver.h"
#include "led_driver.h"
#include "seven_segment_driver.h"
#include "timebase_driver.h"

/* Private includes */

/* Private typedef */

/* Private enum */

/* Private struct */

/* Private union */

/* Private define */
#define MAIN_SEG7_UPDATE_INTERVAL_MS (1000U)
#define MAIN_SEG7_DIGIT_MAX          (9U)

/* Private macro */

/* Private constants */

/* Private variables */

/* External variables */

/* Private function prototypes */

/* Private user code */

/* Main function, if applicable */
int main(void)
{
    uint32_t digit_value;
    uint32_t previous_timestamp_ms;
    uint32_t current_timestamp_ms;

    LED_Init();
    BUTTON_Init();
    SEG7_Init();
    TIMEBASE_Init();

    digit_value = 0U;
    previous_timestamp_ms = TIMEBASE_GetMilliseconds();
    SEG7_DisplayDigit(digit_value);

    while (1U)
    {
        current_timestamp_ms = TIMEBASE_GetMilliseconds();

        if ((current_timestamp_ms - previous_timestamp_ms) >= MAIN_SEG7_UPDATE_INTERVAL_MS)
        {
            previous_timestamp_ms = current_timestamp_ms;
            SEG7_DisplayDigit(digit_value);

            digit_value++;
            if (digit_value > MAIN_SEG7_DIGIT_MAX)
            {
                digit_value = 0U;
            }
        }
    }
}

/* Public functions */

/* Callback functions */

/* Private functions */

